baseURL = 'https://pedroanastacio.com/'

title = 'Pedro Anastácio'

metaKeywords = [
  "software engineering",
  "productivity",
  "blog",
  "solutions architect",
  "pedro anastacio",
  "leadership",
]

enableRobotsTXT = true

defaultContentLanguage = "en"
languageCode = "en"

theme = "gokarna"

pygmentsStyle = "catppuccin-macchiato"

# Global Configuration
[params]
avatarURL = "/images/pedro.jpg"

description = "Software Engineering, Productivity and probably a bit more."

showPostsOnHomePage = "recent"
numberPostsOnHomePage = 4

togglePreviousAndNextButtons = "true"

socialIcons = [
  { name = "twitter", url = "https://x.com/PGRAnastacio" },
  { name = "linkedin", url = "https://www.linkedin.com/in/pedro-anast%C3%A1cio-99630a1/" },
  { name = "github", url = "https://github.com/nastase" },
  { name = "email", url = "mailto:pedro@nastech.pt" },
]

customHeadHTML = """

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JY8MGEBLL5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JY8MGEBLL5');
</script>
"""

footer = "Pedro Anastácio"

# Menu configuration

[menu]
[[menu.main]]
name = "Home"
pre = "<span data-feather='home'></span>"
url = "/"
weight = 1

[[menu.main]]
name = "Résumé"
pre = "<span data-feather='briefcase'></span>"
url = "/work/resume"
weight = 2

[[menu.main]]
name = "Posts"
pre = "<span data-feather='book'></span>"
url = "/posts/"
weight = 3

[[menu.main]]
name = "Tags"
pre = "<span data-feather='tag'></span>"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "github"
url = "https://github.com/nastase"
weight = 5
pre = "<span data-feather='github'></span>"
post = ""

[[menu.main]]
identifier = "linkedin"
url = "https://www.linkedin.com/in/pedro-anast%C3%A1cio-99630a1/"
weight = 5
pre = "<span data-feather='linkedin'></span>"
post = ""

[[menu.main]]
identifier = "rss"
pre = "<span data-feather='rss'></span>"
url = "/index.xml"
weight = 7

[minify]
minifyOutput = true
